name: test
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        nim-branch: [version-1-6, version-2-0, devel]
    name: nim-${{ matrix.nim-branch }}
    runs-on: ubuntu-latest
    steps:
    - name: checkout Nim
      uses: actions/checkout@v3
      with:
        repository: nim-lang/Nim
        ref: ${{ matrix.nim-branch }}
        path: Nim
    - name: set path to nim
      run: echo "::add-path::${{ github.workspace }}/Nim/bin"
    - name: build Nim & nimble
      working-directory: Nim
      run: |
        . ci/funs.sh
        nimBuildCsourcesIfNeeded
        ./bin/nim c --noNimblePath --skipUserCfg --skipParentCfg --hints:off koch
        ./koch boot -d:release -d:danger --skipUserCfg --skipParentCfg --hints:off
        ./koch nimble -d:release -d:danger --skipUserCfg --skipParentCfg --hints:off
    - name: checkout
      uses: actions/checkout@v3
      with:
        path: MDevolve
    - name: install
      working-directory: MDevolve
      run: nimble install -y
    - name: test
      working-directory: MDevolve
      run: nimble test
