name: test
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        nim-branch: [version-1-2, devel]
    name: nim-${{ matrix.nim-branch }}
    runs-on: ubuntu-latest
    steps:
    - name: checkout Nim
      uses: actions/checkout@v2
      with:
        repository: nim-lang/Nim
        ref: ${{ matrix.nim-branch }}
        path: Nim
    - name: checkout Nim csources
      uses: actions/checkout@v2
      with:
        repository: nim-lang/csources
        path: Nim/csources
    - name: set path to nim
      run: echo "::add-path::${{ github.workspace }}/Nim/bin"
    - name: build Nim csources
      working-directory: Nim/csources
      run: make -j $(nproc)
    - name: build Nim & nimble
      working-directory: Nim
      run: |
        nim c koch
        ./koch boot -d:release -d:danger
        ./koch nimble -d:release -d:danger
    - name: checkout
      uses: actions/checkout@v2
      with:
        path: MDevolve
    - name: install
      working-directory: MDevolve
      run: nimble install -y
    - name: test
      working-directory: MDevolve
      run: nimble test
